### ISSUE TITLE
Unable to compile on PHP 5.6/OSX

### ISSUE THREAD

**Issue by Fuitad** [weltling/phurple#2]
Heya,

I tried compiling the master branch on OSX but I'm getting duplicate symbol errors. Is there anything I can do to fix this? :)

Thanks!

```
$ make
/bin/sh /opt/src/phurple/libtool --mode=compile cc  -I. -I/opt/src/phurple -DPHP_ATOM_INC -I/opt/src/phurple/include -I/opt/src/phurple/main -I/opt/src/phurple -I/opt/include/php -I/opt/include/php/main -I/opt/include/php/TSRM -I/opt/include/php/Zend -I/opt/include/php/ext -I/opt/include/php/ext/date/lib -I/usr/local/include/glib-2.0 -I/usr/local/lib/glib-2.0/include -I/usr/local/include/libpurple  -DHAVE_CONFIG_H  -g -O2 -g3   -c /opt/src/phurple/phurple.c -o phurple.lo 
mkdir .libs
 cc -I. -I/opt/src/phurple -DPHP_ATOM_INC -I/opt/src/phurple/include -I/opt/src/phurple/main -I/opt/src/phurple -I/opt/include/php -I/opt/include/php/main -I/opt/include/php/TSRM -I/opt/include/php/Zend -I/opt/include/php/ext -I/opt/include/php/ext/date/lib -I/usr/local/include/glib-2.0 -I/usr/local/lib/glib-2.0/include -I/usr/local/include/libpurple -DHAVE_CONFIG_H -g -O2 -g3 -c /opt/src/phurple/phurple.c  -fno-common -DPIC -o .libs/phurple.o
/bin/sh /opt/src/phurple/libtool --mode=compile cc  -I. -I/opt/src/phurple -DPHP_ATOM_INC -I/opt/src/phurple/include -I/opt/src/phurple/main -I/opt/src/phurple -I/opt/include/php -I/opt/include/php/main -I/opt/include/php/TSRM -I/opt/include/php/Zend -I/opt/include/php/ext -I/opt/include/php/ext/date/lib -I/usr/local/include/glib-2.0 -I/usr/local/lib/glib-2.0/include -I/usr/local/include/libpurple  -DHAVE_CONFIG_H  -g -O2 -g3   -c /opt/src/phurple/client.c -o client.lo 
 cc -I. -I/opt/src/phurple -DPHP_ATOM_INC -I/opt/src/phurple/include -I/opt/src/phurple/main -I/opt/src/phurple -I/opt/include/php -I/opt/include/php/main -I/opt/include/php/TSRM -I/opt/include/php/Zend -I/opt/include/php/ext -I/opt/include/php/ext/date/lib -I/usr/local/include/glib-2.0 -I/usr/local/lib/glib-2.0/include -I/usr/local/include/libpurple -DHAVE_CONFIG_H -g -O2 -g3 -c /opt/src/phurple/client.c  -fno-common -DPIC -o .libs/client.o
/bin/sh /opt/src/phurple/libtool --mode=compile cc  -I. -I/opt/src/phurple -DPHP_ATOM_INC -I/opt/src/phurple/include -I/opt/src/phurple/main -I/opt/src/phurple -I/opt/include/php -I/opt/include/php/main -I/opt/include/php/TSRM -I/opt/include/php/Zend -I/opt/include/php/ext -I/opt/include/php/ext/date/lib -I/usr/local/include/glib-2.0 -I/usr/local/lib/glib-2.0/include -I/usr/local/include/libpurple  -DHAVE_CONFIG_H  -g -O2 -g3   -c /opt/src/phurple/conversation.c -o conversation.lo 
 cc -I. -I/opt/src/phurple -DPHP_ATOM_INC -I/opt/src/phurple/include -I/opt/src/phurple/main -I/opt/src/phurple -I/opt/include/php -I/opt/include/php/main -I/opt/include/php/TSRM -I/opt/include/php/Zend -I/opt/include/php/ext -I/opt/include/php/ext/date/lib -I/usr/local/include/glib-2.0 -I/usr/local/lib/glib-2.0/include -I/usr/local/include/libpurple -DHAVE_CONFIG_H -g -O2 -g3 -c /opt/src/phurple/conversation.c  -fno-common -DPIC -o .libs/conversation.o
/bin/sh /opt/src/phurple/libtool --mode=compile cc  -I. -I/opt/src/phurple -DPHP_ATOM_INC -I/opt/src/phurple/include -I/opt/src/phurple/main -I/opt/src/phurple -I/opt/include/php -I/opt/include/php/main -I/opt/include/php/TSRM -I/opt/include/php/Zend -I/opt/include/php/ext -I/opt/include/php/ext/date/lib -I/usr/local/include/glib-2.0 -I/usr/local/lib/glib-2.0/include -I/usr/local/include/libpurple  -DHAVE_CONFIG_H  -g -O2 -g3   -c /opt/src/phurple/account.c -o account.lo 
 cc -I. -I/opt/src/phurple -DPHP_ATOM_INC -I/opt/src/phurple/include -I/opt/src/phurple/main -I/opt/src/phurple -I/opt/include/php -I/opt/include/php/main -I/opt/include/php/TSRM -I/opt/include/php/Zend -I/opt/include/php/ext -I/opt/include/php/ext/date/lib -I/usr/local/include/glib-2.0 -I/usr/local/lib/glib-2.0/include -I/usr/local/include/libpurple -DHAVE_CONFIG_H -g -O2 -g3 -c /opt/src/phurple/account.c  -fno-common -DPIC -o .libs/account.o
/opt/src/phurple/account.c:350:10: warning: 4 enumeration values not handled in switch: 'PURPLE_PREF_NONE', 'PURPLE_PREF_STRING_LIST', 'PURPLE_PREF_PATH'... [-Wswitch]
                switch(setting->type) {
                       ^
1 warning generated.
/bin/sh /opt/src/phurple/libtool --mode=compile cc  -I. -I/opt/src/phurple -DPHP_ATOM_INC -I/opt/src/phurple/include -I/opt/src/phurple/main -I/opt/src/phurple -I/opt/include/php -I/opt/include/php/main -I/opt/include/php/TSRM -I/opt/include/php/Zend -I/opt/include/php/ext -I/opt/include/php/ext/date/lib -I/usr/local/include/glib-2.0 -I/usr/local/lib/glib-2.0/include -I/usr/local/include/libpurple  -DHAVE_CONFIG_H  -g -O2 -g3   -c /opt/src/phurple/connection.c -o connection.lo 
 cc -I. -I/opt/src/phurple -DPHP_ATOM_INC -I/opt/src/phurple/include -I/opt/src/phurple/main -I/opt/src/phurple -I/opt/include/php -I/opt/include/php/main -I/opt/include/php/TSRM -I/opt/include/php/Zend -I/opt/include/php/ext -I/opt/include/php/ext/date/lib -I/usr/local/include/glib-2.0 -I/usr/local/lib/glib-2.0/include -I/usr/local/include/libpurple -DHAVE_CONFIG_H -g -O2 -g3 -c /opt/src/phurple/connection.c  -fno-common -DPIC -o .libs/connection.o
/bin/sh /opt/src/phurple/libtool --mode=compile cc  -I. -I/opt/src/phurple -DPHP_ATOM_INC -I/opt/src/phurple/include -I/opt/src/phurple/main -I/opt/src/phurple -I/opt/include/php -I/opt/include/php/main -I/opt/include/php/TSRM -I/opt/include/php/Zend -I/opt/include/php/ext -I/opt/include/php/ext/date/lib -I/usr/local/include/glib-2.0 -I/usr/local/lib/glib-2.0/include -I/usr/local/include/libpurple  -DHAVE_CONFIG_H  -g -O2 -g3   -c /opt/src/phurple/buddy.c -o buddy.lo 
 cc -I. -I/opt/src/phurple -DPHP_ATOM_INC -I/opt/src/phurple/include -I/opt/src/phurple/main -I/opt/src/phurple -I/opt/include/php -I/opt/include/php/main -I/opt/include/php/TSRM -I/opt/include/php/Zend -I/opt/include/php/ext -I/opt/include/php/ext/date/lib -I/usr/local/include/glib-2.0 -I/usr/local/lib/glib-2.0/include -I/usr/local/include/libpurple -DHAVE_CONFIG_H -g -O2 -g3 -c /opt/src/phurple/buddy.c  -fno-common -DPIC -o .libs/buddy.o
/bin/sh /opt/src/phurple/libtool --mode=compile cc  -I. -I/opt/src/phurple -DPHP_ATOM_INC -I/opt/src/phurple/include -I/opt/src/phurple/main -I/opt/src/phurple -I/opt/include/php -I/opt/include/php/main -I/opt/include/php/TSRM -I/opt/include/php/Zend -I/opt/include/php/ext -I/opt/include/php/ext/date/lib -I/usr/local/include/glib-2.0 -I/usr/local/lib/glib-2.0/include -I/usr/local/include/libpurple  -DHAVE_CONFIG_H  -g -O2 -g3   -c /opt/src/phurple/buddylist.c -o buddylist.lo 
 cc -I. -I/opt/src/phurple -DPHP_ATOM_INC -I/opt/src/phurple/include -I/opt/src/phurple/main -I/opt/src/phurple -I/opt/include/php -I/opt/include/php/main -I/opt/include/php/TSRM -I/opt/include/php/Zend -I/opt/include/php/ext -I/opt/include/php/ext/date/lib -I/usr/local/include/glib-2.0 -I/usr/local/lib/glib-2.0/include -I/usr/local/include/libpurple -DHAVE_CONFIG_H -g -O2 -g3 -c /opt/src/phurple/buddylist.c  -fno-common -DPIC -o .libs/buddylist.o
/bin/sh /opt/src/phurple/libtool --mode=compile cc  -I. -I/opt/src/phurple -DPHP_ATOM_INC -I/opt/src/phurple/include -I/opt/src/phurple/main -I/opt/src/phurple -I/opt/include/php -I/opt/include/php/main -I/opt/include/php/TSRM -I/opt/include/php/Zend -I/opt/include/php/ext -I/opt/include/php/ext/date/lib -I/usr/local/include/glib-2.0 -I/usr/local/lib/glib-2.0/include -I/usr/local/include/libpurple  -DHAVE_CONFIG_H  -g -O2 -g3   -c /opt/src/phurple/group.c -o group.lo 
 cc -I. -I/opt/src/phurple -DPHP_ATOM_INC -I/opt/src/phurple/include -I/opt/src/phurple/main -I/opt/src/phurple -I/opt/include/php -I/opt/include/php/main -I/opt/include/php/TSRM -I/opt/include/php/Zend -I/opt/include/php/ext -I/opt/include/php/ext/date/lib -I/usr/local/include/glib-2.0 -I/usr/local/lib/glib-2.0/include -I/usr/local/include/libpurple -DHAVE_CONFIG_H -g -O2 -g3 -c /opt/src/phurple/group.c  -fno-common -DPIC -o .libs/group.o
/bin/sh /opt/src/phurple/libtool --mode=compile cc  -I. -I/opt/src/phurple -DPHP_ATOM_INC -I/opt/src/phurple/include -I/opt/src/phurple/main -I/opt/src/phurple -I/opt/include/php -I/opt/include/php/main -I/opt/include/php/TSRM -I/opt/include/php/Zend -I/opt/include/php/ext -I/opt/include/php/ext/date/lib -I/usr/local/include/glib-2.0 -I/usr/local/lib/glib-2.0/include -I/usr/local/include/libpurple  -DHAVE_CONFIG_H  -g -O2 -g3   -c /opt/src/phurple/presence.c -o presence.lo 
 cc -I. -I/opt/src/phurple -DPHP_ATOM_INC -I/opt/src/phurple/include -I/opt/src/phurple/main -I/opt/src/phurple -I/opt/include/php -I/opt/include/php/main -I/opt/include/php/TSRM -I/opt/include/php/Zend -I/opt/include/php/ext -I/opt/include/php/ext/date/lib -I/usr/local/include/glib-2.0 -I/usr/local/lib/glib-2.0/include -I/usr/local/include/libpurple -DHAVE_CONFIG_H -g -O2 -g3 -c /opt/src/phurple/presence.c  -fno-common -DPIC -o .libs/presence.o
/bin/sh /opt/src/phurple/libtool --mode=link cc -DPHP_ATOM_INC -I/opt/src/phurple/include -I/opt/src/phurple/main -I/opt/src/phurple -I/opt/include/php -I/opt/include/php/main -I/opt/include/php/TSRM -I/opt/include/php/Zend -I/opt/include/php/ext -I/opt/include/php/ext/date/lib -I/usr/local/include/glib-2.0 -I/usr/local/lib/glib-2.0/include -I/usr/local/include/libpurple  -DHAVE_CONFIG_H  -g -O2 -g3   -o phurple.la -export-dynamic -avoid-version -prefer-pic -module -rpath /opt/src/phurple/modules  phurple.lo client.lo conversation.lo account.lo connection.lo buddy.lo buddylist.lo group.lo presence.lo -Wl,-rpath,/usr/local/lib -L/usr/local/lib -lpurple
cc ${wl}-flat_namespace ${wl}-undefined ${wl}suppress -o .libs/phurple.so -bundle  .libs/phurple.o .libs/client.o .libs/conversation.o .libs/account.o .libs/connection.o .libs/buddy.o .libs/buddylist.o .libs/group.o .libs/presence.o  -L/usr/local/lib -lpurple  -Wl,-rpath -Wl,/usr/local/lib
duplicate symbol _default_phurple_obj_handlers in:
    .libs/phurple.o
    .libs/client.o
duplicate symbol _default_phurple_obj_handlers in:
    .libs/phurple.o
    .libs/conversation.o
duplicate symbol _default_phurple_obj_handlers in:
    .libs/phurple.o
    .libs/account.o
duplicate symbol _default_phurple_obj_handlers in:
    .libs/phurple.o
    .libs/connection.o
duplicate symbol _default_phurple_obj_handlers in:
    .libs/phurple.o
    .libs/buddy.o
duplicate symbol _default_phurple_obj_handlers in:
    .libs/phurple.o
    .libs/buddylist.o
duplicate symbol _default_phurple_obj_handlers in:
    .libs/phurple.o
    .libs/group.o
duplicate symbol _default_phurple_obj_handlers in:
    .libs/phurple.o
    .libs/presence.o
ld: 8 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [phurple.la] Error 1
```

**Comment by king4415** [comment]
Das

**Comment by king4415** [comment]
Juli
